# Generated by Django 3.1.5 on 2021-01-15 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72, null=True)),
                ('surname', models.CharField(max_length=72, null=True)),
                ('username', models.CharField(max_length=72)),
                ('email', models.CharField(max_length=72, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=72)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed'), ('TR', 'Triaged'), ('PR', 'Progress')], default='OP', max_length=2)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.group')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ai.account')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ai.group')),
            ],
            options={
                'permissions': [('close_ticket', 'Can remove a task by setting its status as closed'), ('change_ticket_status', 'Can change the status of tasks')],
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_from', models.IntegerField()),
                ('to', models.IntegerField()),
                ('subject', models.CharField(max_length=998)),
                ('content', models.CharField(max_length=998)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.account')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ai.account')),
            ],
            options={
                'permissions': [('close_ticket', 'Can remove a task by setting its status as closed'), ('comment_ticket', 'Can leave a comment on ticket')],
            },
        ),
    ]
