# Generated by Django 3.1.5 on 2021-02-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_auto_20210121_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='scores',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
