# Generated by Django 3.1.5 on 2021-02-01 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_group_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fine',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='inizio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
