# Generated by Django 3.1.5 on 2021-02-01 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_auto_20210201_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fine',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='inizio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
