# Generated by Django 3.1.5 on 2021-02-01 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_auto_20210201_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fine',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 20, 58, 56, 351327)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='inizio',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 20, 58, 56, 351307)),
        ),
    ]
