# Generated by Django 3.1.5 on 2021-02-01 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_auto_20210201_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fine',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 20, 59, 29, 352818)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='inizio',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 20, 59, 29, 352785)),
        ),
    ]
