# Generated by Django 3.1.5 on 2021-02-01 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_auto_20210201_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fine',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 21, 8, 19, 497126)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='inizio',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 21, 8, 19, 497083)),
        ),
    ]
