# Generated by Django 3.1.5 on 2021-02-01 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_auto_20210201_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fine',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 21, 26, 57, 331545)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='inizio',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 21, 26, 57, 331504)),
        ),
    ]
