# Generated by Django 3.1.5 on 2021-02-01 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_auto_20210201_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='scores',
            field=models.CharField(default={}, max_length=10000),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fine',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 21, 46, 47, 324548)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='inizio',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 21, 46, 47, 324477)),
        ),
    ]
