# Generated by Django 3.1.5 on 2021-02-01 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_auto_20210201_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fine',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 21, 49, 18, 142965)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='inizio',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 21, 49, 18, 142885)),
        ),
    ]
